import digitalclock
print ("Horizontal line, width = 5:")
temp = digitalclock.horizontal_line(5, '*')
print (temp)
print ()
print ("Horizontal line, width = 10:")
temp = digitalclock.horizontal_line(10, '+')
print (temp)
print ()
print ("Horizontal line, width = 15:")
temp = digitalclock.horizontal_line(15, 'z')
print (temp)
print ()
print ("Vertical Line, shift=0; height=3:")
temp = digitalclock.vertical_line(0, 3, '!')
print (temp)
print ()
print ("Vertical Line, shift=3; height=3:")
temp = digitalclock.vertical_line(3, 3, '&')
print (temp)
print ()
print ("Vertical Line, shift=6; height=5:")
temp = digitalclock.vertical_line(6, 5, '$')
print (temp)
print ()
print ("Two Vertical Lines, width=3; height=3:")
temp = digitalclock.two_vertical_lines(3, 3, '^')
print (temp)
print ()
print ("Two Vertical Lines, width=4; height=5:")
temp = digitalclock.two_vertical_lines(4, 5, '@')
print (temp)
print ()
print ("Two Vertical Lines, width=5; height=2:")
temp = digitalclock.two_vertical_lines(5, 2, '#')
print (temp)
print ()



#problem 2B

temp = digitalclock.number_0(5, '*')
print(temp)
print()
temp = digitalclock.number_1(5, '*')
print(temp)
print()
temp = digitalclock.number_2(5, '*')
print(temp)
print()
temp = digitalclock.number_3(5, '*')
print(temp)
print()
temp = digitalclock.number_4(5, '*')
print(temp)
print()
temp = digitalclock.number_5(5, '*')
print(temp)
print()
temp = digitalclock.number_6(5, '*')
print(temp)
print()
temp = digitalclock.number_7(5, '*')
print(temp)
print()
temp = digitalclock.number_8(5, '*')
print(temp)
print()
temp = digitalclock.number_9(5, '*')
print(temp)
print()

#problem 2C
digitalclock.print_number(0, 5, '*')
digitalclock.print_number(1, 6, '*')
digitalclock.print_number(2, 7, '*')
digitalclock.print_number(3, 8, '*')
digitalclock.print_number(4, 9, '*')
digitalclock.print_number(5, 10, '*')
digitalclock.print_number(6, 11, '*')
digitalclock.print_number(7, 12, '*')
digitalclock.print_number(8, 13, '*')
digitalclock.print_number(9, 14, '*')


# problem 2D
temp = digitalclock.plus(6, '*')
print(temp)
print()
temp = digitalclock.minus(5, '*')
print(temp)

# problem 2E
answer1 = digitalclock.check_answer(1, 2, 3, "+")
print(answer1)
answer2 = digitalclock.check_answer(1, 2, -1, "-")
print(answer2)
answer3 = digitalclock.check_answer(9, 5, 3, "+")
print(answer3)
answer4 = digitalclock.check_answer(8, 2, 4, "-")
print(answer4)


#problem 2f

